# Generated by Django 4.0 on 2021-12-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('prenom', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
