# Generated by Django 4.0 on 2021-12-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('idProduct', models.IntegerField()),
                ('date', models.DateField()),
                ('classe', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
