# Generated by Django 4.0 on 2021-12-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
