# Generated by Django 4.0 on 2021-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_profil_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='idProduct',
            field=models.CharField(default='', max_length=255),
        ),
    ]
